language: c++
install:
  - git clone https://github.com/bitcoin/secp256k1
  - cd secp256k1
  - ./autogen.sh && ./configure && make && sudo make install
script:
  - cmake .
  - make
  - ./cryptocoin_test
compiler:
  - clang
  - gcc
package:
  - cmake
